<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Filter_Floating_Average" Id="{fe9c650f-6f25-494f-9fc8-12e4ba645b55}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Filter_Floating_Average
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>