<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Filter_LowPass" Id="{09a317c6-1b69-42ae-bf7c-6979c46a34ca}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Filter_LowPass
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>