<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Filter_HighPass" Id="{b92737df-725a-4f48-b1ee-dd51323b0d67}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Filter_HighPass
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>