<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Generator_Sine" Id="{e350ad4d-7b69-4ec8-912a-5345833cc920}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Generator_Sine
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>