<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Generator_Triangular" Id="{d22016f6-3df3-4b82-8257-88b394ede0df}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Generator_Triangular
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>