<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Generator_Random" Id="{481933fa-f384-4460-a832-56b1a0a61ce6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Generator_Random
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>