<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Generator_PWM" Id="{5ece2670-375c-49d6-b13c-78f48d48c80c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Generator_PWM
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>