<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Generator_Square" Id="{56bac490-8773-4d84-b773-ccc156e890f2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Generator_Square
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>